name: Epic Weekly Free Games

on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 16 * * *"
  # Run manually from the Actions tab
  workflow_dispatch:

jobs:
  Free-Games-Publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python
        run: |
          python main.py
      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update Epic Weekly Free Games" -a
      - name: Push Files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
